server:
  host: "localhost"
  port: "8123"
  public_host: "http://localhost:8123"
db:
  # For server
  # host: "dpg-cp3e7jvsc6pc73fn8kq0-a.oregon-postgres.render.com"

  # For localhost
  host: "localhost"

  port: "5432"

  # For localhost
  dbname: "ulab-market-v2"

  # For server
  # dbname: "ulab_market_busa"
  
  # For localhost
  sslmode: "disable"

  # For server
  # sslmode: "require"
  migrations: "migrations"
redis:
  host: "localhost"
  port: "6379"
smtp:
  email:
    host: "smtp.gmail.com"
    port: "587"
    sender: "ecommerce.ulab@gmail.com"
filestorage:
  url: "ulab-market.appspot.com"
media:
  category_photo_max_size: 2 # mb
  product_photo_max_size: 2 # mb
  product_max_photo_count: 10 # 10 photos maximum

  product_video_max_size: 3 # mb
  product_max_video_count: 3