server:
  host: "0.0.0.0"
  port: "10000"
  public_host: "https://ulab-market-v2-n6zf.onrender.com"
db:
  # host: "dpg-cp3e7jvsc6pc73fn8kq0-a.oregon-postgres.render.com"
  host: "128.140.40.52"
  port: "5434"
  # dbname: "ulab_market_busa"
  dbname: "ulab-market-v2"
  sslmode: "require"
  migrations: "migrations"
redis:
  host: "red-cp3e81vsc6pc73fn8qfg"
  port: "6379"
smtp:
  email:
    host: "smtp.gmail.com"
    port: "587"
    sender: "ecommerce.ulab@gmail.com"
filestorage:
  url: "ulab-market.appspot.com"
media:
    category_photo_max_size: 2 # mb
    product_photo_max_size: 3 # mb
    product_max_photo_count: 10 # 10 photos maximum

    product_video_max_size: 3 # mb
    product_max_video_count: 3